User:
    type: entity
    table: user
    uniqueConstraints:
        email:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        prenom:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        telephone:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        adresse:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        ville:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        codePostal:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: code_postal
        pays:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        mdp:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
